### ISSUE TITLE
Big Picture Mode overhaul broke the plugin

### ISSUE THREAD

**Issue by funkmaster5k** [adambiser/agk-steam-plugin#3]
First of all thank you so much for creating this awesome plugin, @adambiser!

I don't know if you take support requests, because you offer everything free of charge / on a donation basis, but if you do: the current Steam Big Picture mode update seems to have broken the plugin. I only get a white screen when using Steam in Big Picture mode with my game utilizing the plugin and trying to access the Steam Overlay. It worked flawlessly before the update. Would you consider looking into this?

Thank you!

**Comment by adambiser** [comment]
Thanks for pointing this out.  I'll look into it as soon as I can to see what the issue is.  I haven't really used Big Picture mode much.

**Comment by adambiser** [comment]
If you don't mind, would you please post steps to reproduce the problem just in case.  Like I mentioned, I haven't used Big Picture mode very much.

**Comment by funkmaster5k** [comment]
> If you don't mind, would you please post steps to reproduce the problem just in case. Like I mentioned, I haven't used Big Picture mode very much.

**Comment by funkmaster5k** [comment]
Somehow I only had the option to "close with comment", so I don't know what's going on there. The issue persists.

You need to access Big Picture Mode by pressing this button in the Steam client
![bigpicture](https://user-images.githubusercontent.com/33531353/200185409-9a308654-aa7a-4735-8368-f11167ecf0db.png)

Afterwards start a game utilizing your plugin. I can supply a key for mine, if you want to test. Try accessing the Steam Overlay and it only shows as a white screen. Doing this outside Big Picture mode let's me access the Steam Overlay normally.

**Comment by adambiser** [comment]
Thanks for the steps to reproduce.  I'll try with my own games to see whether they have this issue first.

There should be a green "Comment" button to the right of "Close with comment".

**Comment by adambiser** [comment]
I'm using an up-to-date client on Windows 10 and don't have this issue.  I tried with Boot Hill Blaster in windowed and fullscreen mode and could see the regular Steam Overlay while running in Big Picture mode.

**Comment by adambiser** [comment]
Are you using the client beta and the -gamepadui parameter when starting the Steam client?

**Comment by adambiser** [comment]
Hmm, tried that and that also worked for me.

**Comment by funkmaster5k** [comment]
It worked before on my Win 11 machine, no beta program. I'll ask a friend, if he has trouble and I will get back to you as soon as possible. Come to think of it: I recently updated my graphics card from a 1080 to a 6800XT. Maybe it's an AMD issue.

**Comment by adambiser** [comment]
This seems related: https://steamcommunity.com/groups/SteamClientBeta/discussions/0/3373782431196464540/
First comment says "RX 6800XT with 22.9.1 driver"

**Comment by funkmaster5k** [comment]
Wow, oddly specific. Looks like it's not because of your plugin. Thanks for looking into this and your help.

**Comment by adambiser** [comment]
I thought so, too.

Thanks for using the plugin.  I'm glad you find it useful.
